version: "3.8"
volumes:
  mysqldata:

networks:
  default:
    driver: bridge

services:
  phpfpm:
    build:
      context: docker/php-fpm
    container_name: php-fpm
    environment:
      TERM: xterm-color
      DATABASE_URL: mysql://user:password@mysql/database
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: "bind"
        source: "./app/"
        target: "/project"
      - type: "bind"
        source: "../"
        target: "/workspace"
    networks:
      - default

  nginx:
    build:
      context: docker/nginx
    container_name: nginx
    ports:
      - 8084:80
    environment:
      TERM: xterm-color
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "my-app.local"
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: bind
        source: "./app/"
        target: "/project"
      - type: bind
        source: "../"
        target: "/workspace"
      - type: bind
        source: "./docker/nginx/nginx.conf"
        target: "/etc/nginx/nginx.conf"
      - type: bind
        source: "./docker/nginx/phpfpm.conf"
        target: "/etc/nginx/conf.d/phpfpm.conf"
      - type: bind
        source: "./docker/nginx/default.conf"
        target: "/etc/nginx/conf.d/default.conf"
    depends_on:
      - phpfpm
    networks:
      - default

  mysql:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - default